name: Feature Request
description: Propose a feature
title: "[feat]: "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What problem does this solve?
    validations:
      required: true
